
name: Run Tests

on: ['push', 'pull_request']


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - snek: 1.8.1
            snekpip: 'naff==1.8.0'
          - snek: latest
            snekpip: naff
          - snek: dev
            snekpip: 'git+https://github.com/Discord-Snake-Pit/Dis-Snek.git@dev'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip mypy flake8 pytest typeguard pytest-cov ${{ matrix.snekpip }}
        pip install -e .
    - uses: PennyDreadfulMTG/setup-linters@main
    - name: Test with mypy
      run: |
        mypy --install-types --non-interactive .
    - name: Test with Flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest
